### PR TITLE
fix(challenges): typos in some basic node and express challenges

### LINKED ISSUE #113: Typo in description : Basic Node and Express - Serve Static Assets
**Describe the bug**
The current description contains this sentence.
*If don’t know what a middleware is, don’t worry.*
It should be 
*If **you** don't...*

**To Reproduce**
1. Go to [challenge](https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/serve-static-assets)
2. Search for `If don't` on the web page.
3. See error

**Screenshots**
screenshot-2018-7-6 welcome to learn freecodecamp

### PR DESCRIPTION
**Pull request by gforce2k5**
fixed a typo in serve static assets challenge and in chain middleware to create a time server

ISSUES CLOSED: #113, #114

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #113, #114

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM :+1:

Thank you for this fix, @gforce2k5.

**Comment by mpmaan** [comment]
@scissorsneedfoodtoo #114 is still open.....is there any reason for that?

**Comment by johnkennedy9147** [comment]
thanks @mpmaan -  closed #114

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting that @mpmaan. I'll keep my eye out for that in the future! And thank you for closing the issue @johnkennedy9147.

**Pull request merged**
