### PR TITLE
fix(challenges): fix broken test bundle url

### PR DESCRIPTION
**Pull request by jmmarco**
#### Description

Hi guys 👋 
For some challenges, I found that the URL for FCC's test bundle is not valid (404).
Updated the old test bundle URL with the new one. I think this issue was not reported, I simply stumbled upon it.

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by jmmarco** [comment]
Here's a screenshot from one of the challenges in which the test bundle URL is a 404:
screen shot 2018-07-20 at 12 08 04 pm

**Comment by jmmarco** [comment]
Hello @scissorsneedfoodtoo, can I get a review for this PR?

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @jmmarco. So sorry for the delay in reviewing your PR. Looking forward to your next contribution!

**Comment by jmmarco** [comment]
Thanks for the review! Happy to contribute 😄

**Pull request merged**
