### PR TITLE
fix(challenges): fix challenge for fallback value of CSS variable

### PR DESCRIPTION
**Pull request by mpmaan**
#### Description

The variable name needs to be incorrect so that the fallback value is used.

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes [freeCodeCamp/#17840](https://github.com/freeCodeCamp/freeCodeCamp/issues/17840),
Closes [freeCodeCamp/#17699](https://github.com/freeCodeCamp/freeCodeCamp/issues/17699),

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@mpmaan, thank you for taking the time to fix this issue.

I did some testing and spotted some things that can be changed.

**Comment by moT01** [comment]
@scissorsneedfoodtoo my intention was to do the opposite (sort of) of what you are saying - you put the typo in the variable declaration, I originally put the typo in where the variable was used (.penguin-top/.penguin-bottom) - the way it stands on the live site is how it was intended (with the typo where the variables were used)...
```
  .penguin {
    --penguin-skin: gray;
    --penguin-belly: white;
    --penguin-beak: orange;
  }
  
  .penguin-top {
    /* change code below */
    background: var(--pengiun-skin, black);
    /* change code above */
  }
  
  .penguin-bottom {
    /* change code below */
    background: var(--pengiun-skin, black);
    /* change code above */
  }
```
either way would work

**Comment by mpmaan** [comment]
@moT01 The second way proposed by @scissorsneedfoodtoo will also change the color of beak and the feet because of the typo `--pengiun-beak: orange` which is not required.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, I'm sorry, I misunderstood. I think I get it now.

So everything up on the live site for the `.penguin` class is correct now, with penguin spelled correctly for all the CSS variables.

However, in `.penguin-top` and `.penguin-bottom` where the variables are used should be misspelled "pengiun-skin". So the user should correct the spelling and set the color to black in both the top and bottom classes for the tests to pass: `background: var(--penguin-skin, black);`.

Is that right?

**Comment by scissorsneedfoodtoo** [comment]
Alright, thank you for bearing with me so far.

One last question, is the preview image also correct? Just want to make sure the CSS variables for the left and right hand weren't also purposefully misspelled and accidentally corrected later:
  
image

**Comment by moT01** [comment]
@scissorsneedfoodtoo yes, the preview is correct - and no, they werent accidentally corrected later

**Comment by scissorsneedfoodtoo** [comment]
Thank you for confirming that and all of your support, @moT01.

Everything LGTM! Thank you for your contribution, @mpmaan, and also for your patience and help with all of this.

**Pull request merged**
