### PR TITLE
fix(challenges): spelling and grammar errors addressed

### PR DESCRIPTION
**Pull request by RyanPisuena**
#### Description
Basic grammar and spellng changes. Comunicate -> communicate

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by joshalling** [comment]
@RyanPisuena It looks like the Travis CI build is failing because your commit message is not in line with the conventional commit format. It should pass if you fix your commit message. You can follow [these steps](https://help.github.com/articles/changing-a-commit-message/) to change your message

**Comment by RyanPisuena** [comment]
@joshalling Thanks for the heads up!

**Comment by joshalling** [comment]
@RyanPisuena I think you misunderstood. You will need to run git commit --amend on you branch to change the actual commit message. If you want me to walk you through it send me a message on [gitter](https://gitter.im/joshalling).

**Comment by RyanPisuena** [comment]
@joshalling Hi there! Ran git command through command prompt :)

**Comment by joshalling** [comment]
Awesome! Now you just need to wait for an issue moderator to check and merge this and you will have your first PR accepted.

**Pull request merged**
