### PR TITLE
fix(challenges): change definition of complementary colors

### LINKED ISSUE #221: The definition of complementary colors.
A few days ago the section on complementary colors was edited to list orange as the complementary color of blue. 

This is a contentious subject with a lot of people because a lot of us (including me) were taught the outdated RYB color model in school and that kind of sticks with us. Most people do not realize that that is no longer accepted and the preference is for the additive RGB or subtractive CMY. Of course, computer graphics are based on the RGB model.

I know people get heated about this subject. People have a habit of assuming that what they were taught in second grade is the gospel truth and can't conceive that Mrs. Magillicutty could be wrong. And sadly, many people have very firm opinions on this without having researched the subject. Color theory is a very complex science and should not be thrown together willy-nilly.

I suggest changing it back to the modern scientific understanding of color, based on the RGB model - the very color model that computer monitors use. A brief note could be added to explain that this is different than what many people were taught and provide a link to relevant material. Wikipedia for example has [a pretty straightforward article](https://en.wikipedia.org/wiki/Complementary_colors) explaining the change.

### PR DESCRIPTION
**Pull request by kevinsmithwebdev**
The old (correct) definition of complementary colors was edited to change it from
the correct RBB model to the outdated RYB description (that many of us were
taught and school.) The challenge is updated to use "yellow" instead of "orange".

ISSUES CLOSED: #221

#### Description

The complementary color definition had been changed to the old RYB model (where blue and orange are
complementary) from the modern RGB (where yellow is blue's complement). I've changed the definition back to the RGB model, changed the challenges back to use yellow as blue's complement, and added a note in the challenge text that this may be different that what we were taught and provided a link to a wikipedia article about color theory.

#### Pre-Submission Checklist

- [X] Your pull request targets the `dev` branch.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [X] All new and existing tests pass the command `npm test`.
- [X] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [X] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #221

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@kevinsmithwebdev, thank you again for raising this issue and volunteering to fix it.

I just have a couple of minor suggestions for the note you added. Turns out there's already a note wrapped in strong tags at the bottom of the description, so I think we can remove the word entirely. Also, what do you think about reordering the first sentence a bit? I was thinking something like the following:

"This may be different than the outdated RYB color model that many of us were taught in school, which has different primary and complementary colors. Modern color theory uses the additive RGB model (like on a computer screen) and the subtractive CMY(K) model (like in printing). Read <a href='https://en.wikipedia.org/wiki/Color_model' target='_blank'>here</a> for more information on this complex subject."

These are just suggestions, though, so let us know if you have another idea.

**Comment by kevinsmithwebdev** [comment]
Sure, I'll take a look at it tomorrow.


Regards,
Kevin Smith

kevinsmithwebdev.com
510-277-2006

**Comment by kevinsmithwebdev** [comment]
@scissorsneedfoodtoo That all sounds good. The only change I will make is because of the reordering of the first sentence I will change "may be" to be "is". In the old sentence "may be" makes sense because the predicate was "what we were taught..." But now the predicate is "the outdated RYB..." and "this" (the RGB model) is different, by definition. There is some conditionallity left in the sentence by the later qualification of "many of us" - leaving the door open that it may be what the camper learned and may not and making the "may be" at the beginning of the sentence redundant. 

So, I will have "This is different than the outdated RYB color model that many of us were taught in school, which has different primary and complementary colors."

I'll push that up now but if it still needs adjustment, let me know.

**Comment by kevinsmithwebdev** [comment]
OK, I pushed the local changes up and it looks like they are automatically being received here (without having to do an additional PR.) I'm still learning this, so please let me know if there is something else I need to do.

**Comment by scissorsneedfoodtoo** [comment]
@kevinsmithwebdev, you're absolutely right, the sentence reads much better that way. 

Everything LGTM! Thank you for all of your hard work on this issue, and congratulations on your first contribution to freeCodeCamp :sparkle: :sparkle:

**Pull request merged**
