### PR TITLE
fix(challenges): changed complemtary color for blue to ORANGE on the …

### PR DESCRIPTION
**Pull request by ByronCoder**
Fixed complementary color issue 

#### Description

Changed challenge Applied Visual Design: Learn about Complementary Colors to use orange has a complementary color of blue as orange is the correct complementary color of blue.  

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17934

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Can someone point out why the test fails? There seem to no change to the length in the PR

**Comment by SubhrajyotiSen** [comment]
I think the CI test fails because of the format of the pull request. The title overflows in the description part. And the "ISSUES CLOSED: #17934" part is repeated. 
You can also remove the spaces inside "[ x]" for them to be rendered as proper checkboxes. Once you make those edits, the test should pass

**Comment by ByronCoder** [comment]
I made the changes to the PR

**Comment by SubhrajyotiSen** [comment]
I just noticed that your commit message has a similar issue too. The commit title is too long. 
Change it to something like

> fix: changed complementary color for blue to orange

Additional info can be stated from the next line. 
So, you will have to do 
`git commit --amend`
edit the commit message and save it
`git push -f origin fix/responsive-web-design-complentary-colors`

**Comment by ByronCoder** [comment]
Thanks, I made the change. Looks like the checks have passed now.

**Comment by SubhrajyotiSen** [comment]
Good work making the prompt  change.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @ByronCoder. We're all really looking forward to your next contribution. Also, thank you @SubhrajyotiSen for helping out with the commit message error. Good looking out!

**Pull request merged**
