### PR TITLE
Typo errors

### PR DESCRIPTION
**Pull request by Nirajn2311**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes [freeCodeCamp/#17697](https://github.com/freeCodeCamp/freeCodeCamp/issues/17697),
[freeCodecamp/#17699](https://github.com/freeCodeCamp/freeCodeCamp/issues/17699), 
[freeCodeCamp/#17654](https://github.com/freeCodeCamp/freeCodeCamp/issues/17654),
[freeCodeCamp/#17685](https://github.com/freeCodeCamp/freeCodeCamp/issues/17685),
[freeCodeCamp/#17725](https://github.com/freeCodeCamp/freeCodeCamp/issues/17725),
[freeCodeCamp/#17721](https://github.com/freeCodeCamp/freeCodeCamp/issues/17721)

#### Description
Fixed Typos.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@Nirajn2311, thank you for this PR to fix all of these typos. Just a couple of things I noticed:

First, could you remove your package-lock.json file? No need to add that.

Next, I'm just wondering why you remove the id from the audio tag in the challenges/01-responsive-web-design/applied-accessibility.json file? It seems like the problem with that challenge is not that the audio tag in the example has an id attribute, just that the test doesn't account for users including one. I believe it's the test for that challenge that needs to be updated, rather than the example itself.

**Comment by Nirajn2311** [comment]
@scissorsneedfoodtoo I have removed package-lock.json and reverted the id attribute commit.

**Comment by scissorsneedfoodtoo** [comment]
@Nirajn2311, shoot, I'm sorry. I didn't explain myself well when I said remove package-lock.json. We don't want to actually delete it, but use `git rm package-lock.json` to remove it from your commit.

No worries, we can revert to an earlier state pretty easily. Here are some steps:

* Make sure you're on the right branch with `git fix/typos`
* Run `git reflog` and you'll see a list of git reference logs.
* Find the version of the branch you want to revert back to, for example `ab6b04b HEAD@{1}: incorrect spelling of conversion(was converstion)`. (NOTE: I don't know what the string of letters and numbers will look like, but it won't be ab6b04b, which is just used as an example.)
* Run `git reset --hard ab6b04b`
* Check things locally to make sure everything's alright. Your package-lock.json file should be back now.
* Run `git reset --soft HEAD^`
* Run `git reset package-lock.json`
* Finally, run `git push -f origin HEAD`

Now package-lock.json should be back in your remote and the Travis build should pass.

I'm sorry again for all the trouble. Please take your time and do this all when you can. Just let us know if you run into any problems along the way and hopefully we can get your changes merged soon.

**Comment by Nirajn2311** [comment]
@scissorsneedfoodtoo sorry about the json file(will fix it tomorrow). Travis failed as it requires a proper format of commit messages and “delete package-lock.json” is not proper.

**Comment by scissorsneedfoodtoo** [comment]
@Nirajn2311, no need to apologize! Thank you for investigating.

Actually I'm the one who should apologize. I was trying to restore your package-lock.json file, and messed up your commit log in the end. You may be able to use the commands above to roll back my changes/commits and restore the file yourself, though. I'm waiting to hear back from @raisedadead for his git command wizardry before I further mess things up with your PR. Either way, I'm very sorry about that!

Hope we can get these checks to pass and get your changes merged soon.

**Comment by Nirajn2311** [comment]
@scissorsneedfoodtoo I don't what I did but somehow I got back package-lock.json .

**Comment by raisedadead** [comment]
```
git checkout dev
git fetch upstream
git checkout dev -- package-lock.json
```

**Comment by Nirajn2311** [comment]
@raisedadead @scissorsneedfoodtoo @Bouncey All typos and grammatical errors have been fixed. The PR can now be merged.

**Comment by scissorsneedfoodtoo** [comment]
:+1: :+1: Awesome! Everything LGTM :+1: :+1: 

Thank you for your PR to fix all of these typos, @Nirajn2311. We're all looking forward to your next contribution!

**Comment by mpmaan** [comment]
@scissorsneedfoodtoo I believe that spelling error (**pengiun** instead of **penguin**) was intentional.
> Add a fallback value of black to the background property of penguin-top and penguin-bottom classes. This style will be applied because of a typo in the variable name.
Now, the test gets passed but the color doesn't get changed to black.

[freeCodeCamp/#17840](https://github.com/freeCodeCamp/freeCodeCamp/issues/17840)

**Comment by scissorsneedfoodtoo** [comment]
@mpmaan, doh! You're absolutely right. I didn't read that challenge description carefully enough.

Would you be interested in changing the spelling back to "pengiun", and maybe also making it a bit more clear in the description that the misspelling is intentional? Even making "Note" bold would be a huge improvement.

**Pull request merged**
