### PR TITLE
Fix regex

### LINKED ISSUE #108: Wrong regex for test : ES6 - Difference between import and require
**Describe the bug**
This test requires to use only `"` around the `path_to_file` for the solution but I think that `'` should work too.

**Screenshots**
screenshot-2018-7-4 es6 understand the differences between import and require learn freecodecamp

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 60

**Additional context**

### PR DESCRIPTION
**Pull request by mpmaan**
#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [ ] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #108

### CODE REVIEW

**Comment by mpmaan** [comment]
@johnkennedy9147 maybe the error from `commitlint-travis` command can be fixed by updating commit message but i don't know why `npm run test` command is throwing error.

**Comment by ValeraS** [comment]
@mpmaan It looks like you'll need to write ' without \

**Comment by johnkennedy9147** [comment]
@mpmaan sorry totally missed there was another error.
I think @ValeraS is correct you do not need to escape the `'` - the `"` is escaped so it is not misinterpreted as the end of the json field.

**Comment by mpmaan** [comment]
@johnkennedy9147 I still don't know why do we use `\\s+` instead of `\s+` or `\"` instead of `"` in the challenges. I hope that changing the commit history won't cause any problem.

**Comment by johnkennedy9147** [comment]
This is javascript within a json text field, it gets processed from a block of text into a line of code - so anywhere a `\` or  `"` needs to remain it must be escaped, using a backslash, otherwise when the json is processed the `\` will be treated as escaping the next character and the `"` would be treated as the end of the json field.

**Comment by mpmaan** [comment]
@johnkennedy9147 Thanks, that makes sense.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @mpmaan. We're all really looking forward to your next contribution.

Also, thank you @ValeraS and @johnkennedy9147 for your support.

**Pull request merged**
