### PR TITLE
fix(challenges): fix regex in a JS challenge

### LINKED ISSUE #269: Feature Request - Git Challenges
#### Is your feature request related to a problem? Please describe.
I think that it will be better if FCC taught users on how to use git as many people who after learning in FCC may start making their own projects and git will be very useful as it is a powerful VCS and to make sure they don't mistakenly delete some files or folders of their projects.(I'm sure most of us have been there when programming).

### PR DESCRIPTION
**Pull request by pom421**
See more details on fix issue https://github.com/freeCodeCamp/learn/issues/269

BREAKING CHANGE:
None

ISSUES CLOSED: #269

#### Pre-Submission Checklist

- [X] Your pull request targets the `dev` branch.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [X] All new and existing tests pass the command `npm test`.
- [X] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [X] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #269

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@pom421, sorry for the delay in reviewing this. All your changes look good! I just noticed a couple of things.

First and most importantly, your commit message has BREAKING CHANGE in it. Even though you wrote "None" it will still cause a major version bump with the next release. I've definitely made this mistake before, and it's something that should really be in the contributor's guide.

Second, I noticed a small typo in the last test. It was already there, but since you're improving this challenge would you mind improving it just a bit more? There were a couple unnecessary backslashes, which caused one of them to appear in the test text.

Here's what the test should look like:

```
        {
          "text": "Your regex should not match <code>\"Timber\"</code> with 30 <code>m</code>'s in it.",
          "testString": "assert(!timRegex.test(\"Ti\" + \"m\".repeat(30) + \"ber\"), 'Your regex should not match <code>\"Timber\"</code> with 30 <code>m</code>\\'s in it.');"
        }
```

To make these changes, just open up your branch in your code editor of choice and update the test. Then using the command line add the file you changed, and just run `git commit --amend` and delete the breaking change from your commit message so it looks like the following:

```
fix(challenges): fix regex in a JS challenge

See more details on fix issue https://github.com/freeCodeCamp/learn/issues/269

ISSUES CLOSED: #269
```

After that, all you need to do is to push up to your branch again and we should see the changes here. Keep in mind that you may need to force push by using `git push -f` if you set the upstream, or `git push -f origin fix-js-regex` if you didn't.

Hope you don't mind doing these things! Let us know if you run into any problems along the way.

**Comment by pom421** [comment]
@scissorsneedfoodtoo I have made as you proposed but there is conflicts now. 

I hope it will be good to you. On my side, I will not be able to change it before 3 weeks (holidays ;))

**Comment by scissorsneedfoodtoo** [comment]
@pom421, thank you for making those changes. No need to worry about the failing build--I was able to fix it on my end.

Congratulations on your first contribution to freeCodeCamp! :sparkle: Looking forward to your next contribution. Enjoy your holiday!

**Pull request merged**
