### PR TITLE
Improve test for last lesson

### PR DESCRIPTION
**Pull request by krtk6160**
Note: This PR was originally submitted to the main freeCodeCamp repo, but I was asked to submit it here instead. Here's a link to the original PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/17588

#### Description

It is possible to pass an empty object to the `.find` function and still pass the test, because all the people in the test have burrito as one of their favorite foods.
Adding another person that doesn't have burrito as one of their favorite foods, and who's initial is lexicographically smaller than 'M' fixes this issue, as passing an empty object will then result in the failure of the test that checks if the `name` of the second person is 'Mario'.

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [ ] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
The test is failing on the commit standard format enforcement step. Amend and force push ...

**Comment by scissorsneedfoodtoo** [comment]
Thank you for taking the time to resubmit this PR, @krtk6160. Unfortunately it seems like the Travis CI build is failing because you don't have a [conventional commit message](https://conventionalcommits.org/#why-use-conventional-commits).

Please take a look at our [Contributor's Guide](https://github.com/freeCodeCamp/curriculum/blob/dev/docs/CONTRIBUTING.md#other-resources) for more information about generating a conventional commit message and updating your pull request so we can merge it. Also, feel free to reach out to us in the comments here or in the [Contributor's Chatroom](https://gitter.im/FreeCodeCamp/Contributors) if you need any assistance.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo do the changes themselves look good?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, just checked it out and everything LGTM.

**Pull request merged**
