### PR TITLE
fix(challenges): Correct a regex in ES6 read-only challenge

### PR DESCRIPTION
**Pull request by thomlom**
The regex testing if the user has entered console.log(SENTENCE); has
been modified. In fact, the regex was broken before.

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17679 in freeCodeCamp's main repository

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @thomlom. Also, thank you for closing your first PR in the main repo and submitting another here. We're all really looking forward to your next contribution!

**Comment by scissorsneedfoodtoo** [comment]
@thearunster, thank you for investigating.

I believe it's because the NPM package of all the recently updated challenges, including this fix, is now version 2.0.0. However, `package.json` for Learn has the following:

`"@freecodecamp/curriculum": "^1.2.1"`

So I think this will have to be manually bumped, as the caret only matches the most recent patch and/or minor version--the last and middle digits--but ignores major releases like the one we just had.

We'll make the change to the above file ASAP!

**Comment by thearunster** [comment]
@scissorsneedfoodtoo , glad to be of help! 
BTW, I only noticed this because there were 2 issues on the freecodecamp repo talking about this problem:
[#17716](https://github.com/freeCodeCamp/freeCodeCamp/issues/17716) and [#17679](https://github.com/freeCodeCamp/freeCodeCamp/issues/17679)

The second one has a lot of people reporting this issue.

**Comment by johnkennedy9147** [comment]
@Bouncey did this yesterday in  #17707 but I guess it hasn't been pushed to production yet.

**Comment by huyenltnguyen** [comment]
@johnkennedy9147 That was an update on the freeCodeCamp repo, but another update needs to be done on the learn repo, I think.

**Pull request merged**
