### PR TITLE
docs(tools): fixed a typo in the challenge "you" => "your"

### PR DESCRIPTION
**Pull request by Marzdor**
ISSUES CLOSED: #17947

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17947

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@Marzdor, sorry that you've been having trouble with this. Hopefully we'll get this sorted out.

You can follow @Nirajn2311's instructions above to reset the changes made to package-lock.json. Alternatively, you can run the following commands:

First, `git checkout upstream/dev -- package-lock.json` will revert changes to the file and get it in line with the one from the main freeCodeCamp/Curriculum dev branch. Then, run `git commit --amend` and exit out of the editor to use the same commit message. Finally, run `git push -f origin fix/debugging-challenge-typo` to push the changes to the package-lock.json file to your branch. We should then see the changes reflected here and will be able to merge your fix.

Let us know if we can help with anything else!

**Comment by Marzdor** [comment]
@scissorsneedfoodtoo I followed @Nirajn2311 instructions and all the checks show passing is there something else that I am missing?

**Comment by Nirajn2311** [comment]
@Marzdor sry I forgot to tell one more thing, you don’t have to include package-lock.json when you commit.

**Comment by Marzdor** [comment]
@Nirajn2311 I figured that but I am not sure how to go about removing it from the commit.

**Comment by scissorsneedfoodtoo** [comment]
@Marzdor, could you follow the steps from my comment above? I tested them with your PR on my machine and it should solve the problem with the package-lock.json file.

**Comment by Marzdor** [comment]
`git checkout upstream/dev -- package-lock.json `says `fatal: invalid reference: upstream/dev`

**Comment by scissorsneedfoodtoo** [comment]
I don't believe you set the upstream yet. In that case, please run `git remote add upstream https://github.com/freeCodeCamp/curriculum.git` and try the commands listed above.

**Comment by Marzdor** [comment]
I have it set and i still get that error
`$ git remote -v`

`origin  https://github.com/Marzdor/curriculum.git (fetch)
origin  https://github.com/Marzdor/curriculum.git (push)
upsteam https://github.com/freeCodeCamp/curriculum.git (fetch)
upsteam https://github.com/freeCodeCamp/curriculum.git (push)
`

**Comment by scissorsneedfoodtoo** [comment]
Ah, I think I see the problem. Seems like your remote is spelled upsteam rather than upstream. Let's rename that first before you go through the steps again:

`git remote rename upsteam upstream`

After that you should be able to go through the steps listed above.

**Comment by Marzdor** [comment]
I renamed it to be upstream and it still gives me the invalid reference

**Comment by scissorsneedfoodtoo** [comment]
That's strange, I'm not sure why you're still getting the error. Could you run `git remote -v` again and post the output?

**Comment by Marzdor** [comment]
I am not sure if if that space between upstream and the url is messing it up but I tried removing it and it always has the space
```
$ git remote -v
origin  https://github.com/Marzdor/curriculum.git (fetch)
origin  https://github.com/Marzdor/curriculum.git (push)
upstream        https://github.com/freeCodeCamp/curriculum.git (fetch)
upstream        https://github.com/freeCodeCamp/curriculum.git (push)

```

**Comment by scissorsneedfoodtoo** [comment]
@Marzdor, that seems fine. I get the same output when I run that command on my machine. Does `git checkout upstream/dev -- package-lock.json` still throw an error?

**Comment by Marzdor** [comment]
Yes, it still gives me the invalid reference error.

**Comment by scissorsneedfoodtoo** [comment]
Sorry that you're still getting the error. We could try looking into the git log and try to figure out what point to roll back to, but I fear we might have polluted the log by messing with the remote name. 

The easiest thing to do now would probably just be to go to the [package-lock] (https://github.com/freeCodeCamp/curriculum/blob/dev/package-lock.json) file in the dev branch, copy it, and paste it over the one in your branch. Not ideal, but it's something I've done in the past when I accidentally committed it.

**Comment by Marzdor** [comment]
After I copy it to my branch do I have to re commit or anything?

**Comment by scissorsneedfoodtoo** [comment]
Yes, you'll have to add the file, run `git commit --amend` to use the same commit message, and force push it to your branch with `git push -f origin fix/debugging-challenge-typo`. After that we should be good.

**Comment by Marzdor** [comment]
Okay, lets see if that worked.

**Comment by Nirajn2311** [comment]
@Marzdor you have included package-lock.json again

**Comment by Marzdor** [comment]
It said it was staggered

**Comment by scissorsneedfoodtoo** [comment]
Looks like you're on the right track, but haven't added the package-lock.json file. Add it by running `git add package-lock.json`, `git commit --amend` again to use the same commit message, and finally `git push -f origin fix/debugging-challenge-typo`.

**Comment by Marzdor** [comment]
Oh, yeah, I think it worked.

**Comment by Nirajn2311** [comment]
@Marzdor it has worked and everything LGTM.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @Marzdor. Sorry about all the trouble with git. Glad you were able to work everything out and we could get your change merged. We're all really looking forward to your next contribution! Also, thank you @Nirajn2311 for your support with this PR!

**Pull request merged**
