### PR TITLE
fix(challenges): fix responsive web design cert claim

### PR DESCRIPTION
**Pull request by huyenltnguyen**
#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

BREAKING CHANGE:
none

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17698

#### Description

Fixed the issue with claiming the Responsive Web Design Certification by giving the 'Build a Personal Portfolio Webpage' project the correct id.

This one was actually fixed twice (https://github.com/freeCodeCamp/freeCodeCamp/pull/17389 and https://github.com/freeCodeCamp/freeCodeCamp/pull/17102), but I don't know why it's still not reflected here. Maybe there is some issue with the recent migration?

Feel free to close my PR if you can somehow rollback/apply the old fixes.

### CODE REVIEW

**Comment by huyenltnguyen** [comment]
Awesome! Thanks for reviewing and merging it so quickly!

**Comment by golden-frog** [comment]
Thanks again for you commitment @huyenltnguyen. Does this mean the problem is fixed now?

**Comment by huyenltnguyen** [comment]
@golden-frog You're so welcome! Thank you for your patience and sorry again about the issue. The fixed was merged to the code base, but it needs to be deployed to take effect. I don't know when the deployment will start (if it did not already) since it's up to the core team, and how long it will take, but I think it should be very soon as many users have been affected by this issue.

All we can do now is to wait. If you're able to claim the certificate at some point, please post a comment in the issue thread to notify other campers. :)

**Comment by GMradu** [comment]
Hi Guys, There is a new challenge under the same issue. So, now you can claim the certificate but when you press again to button to actually see the certificate you get a Gateway 502 error. Any thoughts about this?

**Comment by huyenltnguyen** [comment]
@GMradu The issue you are experiencing is probably different than this one. Please open a new issue [here](https://github.com/freeCodeCamp/freeCodeCamp/issues) with as much information as possible. Thanks!

**Pull request merged**
