### PR TITLE
feat(interview-prep): Porting Rosetta problems

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by raisedadead** [comment]
This commit has a duplicate challenges. And hence breaking the build. I have isolated the commit and making a fresh PR.

@NitronR Can you please take a look and remove the duplicate challenges?

/cc @scissorsneedfoodtoo

**Comment by NitronR** [comment]
@raisedadead I checked the commit. Sorry, but I failed to locate any duplicate challenges. I am gonna check again. If you know about the names of any duplicate problems, please inform me about them. I will make the changes.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I'm on it. Will take a look at the new challenges included here!

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I think that this might have been one of the earlier commits that you ported earlier. That could be what's causing the problem here. @NitronR's latest PR should be [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/17635) with this commit: ae054926c8fb5af44ef5208f44a2b73ec7f1b8df

Would it be better to close this PR and for @NitronR to reopen it in this repo?

**Comment by NitronR** [comment]
Found the problem. The "I before E except after C" problem has a duplicate ID. Just have to update the ID.

**Comment by raisedadead** [comment]
@NitronR Yes that is correct. You should be able to generate a new mongo object id. I guess we have had instructions on it in the past.

**Comment by NitronR** [comment]
OK, thanks.

**Comment by NitronR** [comment]
The duplicate ID was not the problem. The problem is that there are 6 duplicate problems in the PR but not in the file in the repository.
[Link to Pull request problem](https://github.com/freeCodeCamp/curriculum/blob/0fcecad9a6762e2d2671451e5999c5b2100660a5/challenges/08-coding-interview-prep/rosetta-code.json#L4829)
[Link to Pull request duplicate problem](https://github.com/freeCodeCamp/curriculum/blob/0fcecad9a6762e2d2671451e5999c5b2100660a5/challenges/08-coding-interview-prep/rosetta-code.json#L5297)
[Link to Repository (No duplicates)](https://github.com/freeCodeCamp/curriculum/blob/77f542a2bdc0e690c9ee047d523c77dd94ae0969/challenges/08-coding-interview-prep/rosetta-code.json#L4829)

**Comment by raisedadead** [comment]
Hi @NitronR you can make changes to this PR.

1. Fork this repo.
2.
    ```
    git clone git@github.com:NitronR/curriculum.git
	git remote add upstream https://github.com/freeCodeCamp/curriculum.git
	git fetch --all --prune
	git checkout -b feat/interview-prep
	```
3. Make your changes
4.
	```
	git push origin
	```
5. Open a pull-request on GitHub, but change the base branch

image


Let me know if you face issues.

**Comment by NitronR** [comment]
@raisedadead Changes done. Travis build is successful. Check the new PR. Thanks for the instructions!!

**Comment by raisedadead** [comment]
@NitronR looks like I have screwed up this one completely. Unfortunately that's a consequence of doing manual merge from cross repo. I am sincerely sorry. 

Can you please make a fresh pull request for the whole curriculum that you were trying to port? Will that be too much work?

**Comment by raisedadead** [comment]
For your reference the original commit is still available on here `https://github.com/freeCodeCamp/curriculum/pull/32/commits/ab9c457a5796fad18c766afd6ebee5398687ead4`

**Comment by raisedadead** [comment]
Oh no wait the changes should actually look like this `https://github.com/freeCodeCamp/curriculum/pull/32/files`

Because we are actually removing duplicate stuff. Is that not correct @scissorsneedfoodtoo @NitronR ??

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, yes, I think part of @NitronR's port here was just formatting like in `https://github.com/freeCodeCamp/curriculum/pull/32/files`, where some unneeded spaces were removed after lines in challenges that were already ported.

But the bulk of the PR was in porting the "K" problems: K-d tree, Kaprekar numbers, Knapsack problem/0-1, and so on. Those don't seem to be included in the latest revision. So maybe the best thing is for @NitronR to revise this PR one more time to include those new "K" challenges and we can take it from there.

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, thank you! Just move them over when you can. The seed files will be deleted from the main repo soon, so future challenges should come here.

**Comment by NitronR** [comment]
@raisedadead I have made a PR for the K problems. Please check if it requires any changes.

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM! :+1: :+1: 

Thanks for this PR, @NitronR.

**Pull request merged**
