### PR TITLE
fix(challenges): fix grid-gap shorthand regex

### LINKED ISSUE #229: Grid Gap shorthand declaration passes without a space between measurements
The grid gap shorthand challenge will pass when the measurements are mashed together.

#### To Reproduce
1. Go to ['...'](https://learn.freecodecamp.org/responsive-web-design/css-grid/add-gaps-faster-with-grid-gap)
2. add the following code in the `.container` rule
```css
grid-gap: 10px20px;
```
3. Click run and the test passes

### PR DESCRIPTION
**Pull request by joshalling**
ISSUES CLOSED: #229

#### Description

This updates the regex to use a `+` instead of a `*` between the two measurements so that it requires at least one space.

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #229

### CODE REVIEW

**Comment by moT01** [comment]
Thanks for contributing! 👍

**Comment by joshalling** [comment]
@moT01 It looks like there was a conflict with this pull request and #233 because of the prettier formatting, and the merge removed my fix.

**Comment by moT01** [comment]
sorry about that, that's my fault - I swear I double checked it when I was resolving that conflict, but I must have deleted the wrong line. Not sure the best way to fix it - probably easiest to just make another PR - Do you want to do that and hopefully I won't mess it up this time? If not, I can.

**Comment by joshalling** [comment]
I can submit another PR later today. Thanks!

**Comment by joshalling** [comment]
@moT01 I just submitted another PR. (#237)

**Pull request merged**
