### PR TITLE
fix(challenges): a sentence didn't make sense, so I modified it

### PR DESCRIPTION
**Pull request by lalov1**
ISSUES CLOSED: #18046

#### Description
Reworded information because it didn't make sense beforehand. 

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/18046

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@lalov1, thank you for taking the time to update this challenge.

Your changes look very good overall, but I think we can further improve the end of the sentence you edited. Since JSON describes the format of the object rather than the object itself, I think the sentence should read something like the following:

`Be careful especially when you're accessing and working with external data in the form of a JSON (JavaScript Object Notation) object.`

Or perhaps:

`Be careful especially when you're accessing and working with external data such as JSON (JavaScript Object Notation).`

There are lots of possible ways to word this, so please let me know if you have another suggestion!

**Comment by lalov1** [comment]
@scissorsneedfoodtoo I think adding "object" at the end should work. Do you want me to fix and resubmit?

**Comment by scissorsneedfoodtoo** [comment]
Sure, that's absolutely fine!

To do that, make sure you're on the right branch with `git checkout fix/text-change`. Make the changes and add the file with `git add challenges/02-javascript-algorithms-and-data-structures/debugging.json`. Then you'll need to use `git commit --amend` to amend your current commit message. It's fine now, so just exit out after that command. Finally, just push back to your branch with `git push -f origin fix/text-change` and we'll see the change reflected here.

**Comment by lalov1** [comment]
@scissorsneedfoodtoo I think I made the fix, but let me know if something went wrong...

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM! :+1: :+1: 

Thank you for taking the time to fix this issue, @lalov1. Looking forward to your next contribution!

**Pull request merged**
