### PR TITLE
fix(challenges): change challengeType to fix help button

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
#### Description

This changes the `challengeType` of some challenges so that their 'Ask for help' buttons redirect to the correct sub-forum, as discussed in freecodecamp/learn#259.  In isolation, this doesn't fix that issue, but it is part of the solution.

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM! Tested all of the challenges you changed, along with many others in each affected section, they all auto populate the correct category in the forum.

Just going to request another review since this PR works in conjunction with https://github.com/freeCodeCamp/learn/pull/284.

**Comment by ojeytonwilliams** [comment]
Hey, @Bouncey, there's a slight issue with that.  Currently `challengeType` modern crops up here https://github.com/freeCodeCamp/learn/blob/2ab773dbad7c60ac5556fdbf26b13265cf3c15c3/src/templates/Challenges/classic/Show.js#L211-L213 and this affects https://github.com/freeCodeCamp/learn/blob/2ab773dbad7c60ac5556fdbf26b13265cf3c15c3/src/templates/Challenges/classic/Show.js#L232-L241

So, changing the `challengeType` to 1 would mean the preview pane would not appear.  Obviously setting `challengeType` to 0 doesn't work either, since that would redirect to the wrong help forum.

**Comment by Bouncey** [comment]
Ohhhhhhhh. 

Yes, thank you for reminding me. Ignore my bumbling then. I need more coffee

**Comment by ojeytonwilliams** [comment]
You're welcome!  By the way, speaking of artifacts, I noticed there is the property 'helpRoom' that's unused.  I couldn't find anywhere it's used, but I forgot about it after I realised how the forum was actually selected.  I should have included that in this PR, but it completely slipped my mind...

**Pull request merged**
