### PR TITLE
fix(challenges): fixed telephone number validator project

### LINKED ISSUE #47: Telephone Number Validator - Examples are not presented on separate lines as expected
**Bug:**
In the challenge description, the examples of valid phone number formats are not presented on separate lines as expected.

Link to the challenge: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator

**Solution:**
This is because HTML doesn't render `\n` to a new line, but a single space instead. We can fix it by replacing all the `\n` characters with `<br>` tags. Here is the line that needs to be edited:
https://github.com/freeCodeCamp/curriculum/blob/34f45d25fb0f2b6959539a892892e48b5768fc57/challenges/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects.json#L370

### PR DESCRIPTION
**Pull request by gforce2k5**
fixed telephone number validator projects to show example telephone numbers on new lines

ISSUES CLOSED: #47

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #47

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@gforce2k5, thank you for submitting a PR to fix this issue. Your changes look good! But I noticed that your changes are from an unknown repository. Did you make your changes directly in the web editor? If so, I'm not sure if we can merge this. Unfortunately, you may have to close this and submit another PR. What do you think, @raisedadead?

**Comment by gforce2k5** [comment]
It happened because I deleted the repo from my user repo after submitting this PR

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo if the changes are good, this maybe merged. If they need to make additional changes, they would have to close and make a fresh PR.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, thank you! I'll keep that in mind for future QAing.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @gforce2k5. We're all really looking forward to your next contributions.

**Pull request merged**
