### PR TITLE
docs(contributing): add Contributing Guide

### LINKED ISSUE #61: Update the Contributing documentation
Some potential contributors are having a problem with the Travis CI test which is checking for commit formats, but this is undocumented.

This repo should have a CONTRIBUTING.md file I guess containing this sort of information?

I am not really aware of the circumstances of moving from the old repo to this new repo- maybe it is appropriate to simply link to the CONTRIBUTING.md file from the old repo.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #61

#### Description

Took the challenge guide from the main repo and reworked it for the Curriculum repo. Moved the
CONTRIBUTING.md file to the root directory. Added an image directory and sample image to more
clearly show how to open a PR and point it to the correct branch, like in the guide in the
main repo.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sorry! I didn't see your response and went to bed. Thank you for making those changes. I'll keep that all in mind for the future.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo oh yes no worries. I was in a rush. 

I have gone ahead and fixed up a lot of the PR commit messages.

The release QA workflow is being documented. But here is the thumb rule:

1. If a PR follows conventional commits, and has only one commit - Use `rebase and merge` option.
2. If a PR has multiple commits, or does not follow conventional commits - Use `Squash`  option

However while using `2.` make sure to empty the description box and the commit message drafted should be in conventional format.

**Comment by raisedadead** [comment]
Under no circumstances we should see a description that has a `BREAKING CHANGE` keyword which results in unwanted major bumps.

And as for the release itself it should be fast forwarded commits into `master` from `dev` and not via PR.

I am documenting this more precisely. Will update you soon.

**Comment by raisedadead** [comment]
But for now, feel free to QA and merge the PRs. I should have updated all of them for you.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, okay! Sorry about all the errors before. I was surprised to see the version numbers going up so quickly on npm. Hopefully with these rules in place the bumps will be small and predictable.

**Pull request merged**
