### PR TITLE
Fix css-grid.json typo

### PR DESCRIPTION
**Pull request by AlanBayWalker**
#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by AlanBayWalker** [comment]
I don't understand why the check failed.

**Comment by raisedadead** [comment]
Hi @AlanBayWalker thanks for contributing. But its expected that you follow the the checklist attached on this PR.

I am afraid you will have to edit the commit message to be conventional.

**Comment by scissorsneedfoodtoo** [comment]
Hi @AlanBayWalker, thank you for taking the time to submit a PR for this issue. Sorry you're having some trouble with the Travis CI build. Should be an easy fix, though.

Like @raisedadead mentioned, you'll have to edit the commit message so it's conventional.

First, go to your branch with `git checkout fix/ccs-grid-typo`

Then, edit your commit message with `git commit --amend`.

Right now your commit is the following:

```
Merge branch 'fix/ccs-grid-typo' of https://github.com/AlanBayWalker/curriculum into fix/ccs-grid-typo

fix: minor css grid typo
```

Just change the text so it reads `fix(challenges): minor css grid typo`

After that, push it back to your fork with `git push --force` and hopefully it will pass the test.

Let us know if you need help with anything.

**Comment by scissorsneedfoodtoo** [comment]
@AlanBayWalker, noticed that the build still isn't passing. Sorry about that! It seems like that might be because your previous commits were not standard, and have either a message or full stop.

@raisedadead, what would be the best course of action here? Would it be best for @AlanBayWalker to squash the previous commits, or can we do that on our end? This is also a very simple edit, so I suppose closing this PR and submitting a fresh one wouldn't be much of a problem either.

**Comment by AlanBayWalker** [comment]
Yeah I'm pretty bad at git and I don't really know how to clear them. I'm
just starting out.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, alright, thank you! Will keep that in mind for the future.

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @AlanBayWalker, and also for bearing with me this whole time. We're all really looking forward to your next contribution.

**Comment by AlanBayWalker** [comment]
Thank you to all of you. I will try extra hard next time, to try to follow
all practices in place.

**Pull request merged**
