### PR TITLE
fix(challenges): removed redundant text from a bootstrap challenge

### LINKED ISSUE #36: Redundant/Repetitive text in guide from previous challenge
**Describe the bug**

The guide in the first challenge contains the same redundant text from the second challenge.
1) https://learn.freecodecamp.org/front-end-libraries/bootstrap/create-a-custom-heading
2) https://learn.freecodecamp.org/front-end-libraries/bootstrap/use-the-bootstrap-grid-to-put-elements-side-by-side

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

This is the redundant text.
`Take for example Bootstrap's........................wide the element should be.`

### PR DESCRIPTION
**Pull request by gforce2k5**
Removed redundant text from create-a-custom-heading bootstrap challenge.
The text also appears in
use-the-bootstrap-grid-to-put-elements-side-by-side challenge.

ISSUES CLOSED: #36

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #36

### CODE REVIEW

**Comment by beaucarnes** [comment]
@gforce2k5 Your pull request changes 463 lines of code. Most of the lines changed have nothing to do with the issue. It looks like many single lines of code are changed to two lines. That is unnecessary for this challenge. You may have accidentally ran an autoformatter on your editor. Can you try this one more time but make sure that you only change lines of code directly related to the issue? It may be easiest to revert your code and make your changes again. Thanks!

**Comment by gforce2k5** [comment]
that hapeend only after i used npm run commit, I'll fix it now

**Comment by gforce2k5** [comment]
I made a mess here I'll close this PR and start over sorry

**Comment by beaucarnes** [comment]
@gforce2k5 No problem. Don't get discouraged! This stuff just takes a while to figure out.

**Pull request closed without merging**
