### PR TITLE
Porting K problems

### PR DESCRIPTION
**Pull request by NitronR**
#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, thank you for porting these! Everything LGTM.

I didn't want to bother you with some edits, so I went ahead and changed some of the challenge descriptions myself. However, the builds keep failing. Not sure if I can do it on my end--I'm sorry about that. Would you mind updating them? Hopefully then the build will pass.

Here are the descriptions:

* K-d tree:

```
      "description": [
        "A k-d tree (short for <i>k</i>-dimensional tree) is a space-partitioning data structure for organizing points in a k-dimensional space. k-d trees are a useful data structure for several applications, such as searches involving a multidimensional search key (e.g. range searches and nearest neighbor searches). k-d trees are a special case of binary space partitioning trees.",
        "k-d trees are not suitable, however, for efficiently finding the nearest neighbor in high dimensional spaces. As a general rule, if the dimensionality is <i>k</i>, the number of points in the data, <i>N</i>, should be <i>N</i> ≫ 2<sup><i>k</i></sup>.",
        "Otherwise, when k-d trees are used with high-dimensional data, most of the points in the tree will be evaluated and the efficiency is no better than exhaustive search, and other methods such as approximate nearest-neighbor are used instead.",
        "Write a function to perform a nearest neighbour search using k-d tree. The function takes two parameters: an array of k-dimensional points, and a single k-dimensional point whose nearest neighbour should be returned by the function. A k-dimensional point will be given as an array of k elements."
      ],
```

* Kaprekar numbers

```
      "description": [
        "A positive integer is a <a href=\"https://en.wikipedia.org/wiki/Kaprekar number\">Kaprekar number</a> if:",
        "<ul><li>It is 1</li><li>The decimal representation of its square may be split once into two parts consisting of positive integers which sum to the original number. </li></ul>",
        "Note that a split resulting in a part consisting purely of 0s is not valid, as 0 is not considered positive.Example Kaprekar numbers:",
        "<ul><li>$2223$ is a Kaprekar number, as $2223 * 2223 = 4941729$, $4941729$ may be split to $494$ and $1729$, and $494 + 1729 = 2223$.</li><li>The series of Kaprekar numbers is known as <a href=\"http://rosettacode.org/wiki/oeis:A006886\">A006886</a>, and begins as $1, 9, 45, 55, ...$.</li></ul>",
        "Write a function that takes a number $n$, a base $bs$, and returns true if the number is a Kaprekar number for the given base. Otherwise, the function returns false."
      ],
```

* Knapsack problem/0-1

```
      "description": [
        "Write a function that solves the knapsack problem that is as follows:",
        "You are given an array of objects representing items to be put in a knapsack. The objects have 3 attributes: name, weight, and value. The items need to be selected so that the total weight does not exceed the maximum weight and the value is maximized.",
        "The function is given the array of objects and the maximum weight as parameters. It should return the maximum total value possible."
      ],
```

* Knapsack problem/Bounded

```
      "description": [
        "Write a function that solves the knapsack problem that is as follows:",
        "You are given an array of objects representing items to be put in a knapsack. The objects have 4 attributes: name, pieces (the number of the particular item), weight, and value. The items need to be selected so that the total weight does not exceed the maximum weight and the value is maximized.",
        "The function is given the array of objects and the maximum weight as parameters. It should return the maximum total value possible."
      ],
```

* Knapsack problem/Continuous

```
      "description": [
        "A thief burgles a butcher's shop, where he can select from some items.",
        "The thief knows the weights and prices of each items.  Because he has a knapsack with a limit on the maximum weight that it can carry, he wants to select the items such that he would have his profit maximized.  He may cut the items;  the item has a reduced price after cutting that is proportional to the original price by the ratio of masses.  That means:  half of an item has half the price of the original.",
        "Write a function that takes an array of objects representing the items available in the shop. Each object has 3 attributes: name, weight, and value. The function also takes the maximum weight as a parameter. The function should return the maximum value possible, and the total weight of the selected items should not exceed the maximum weight."
      ],
```

* Knapsack problem/Unbounded

```
      "description": [
        "A traveler gets diverted and has to make an unscheduled stop in what turns out to be Shangri La.  Opting to leave, he is allowed to take as much as he likes of the items available there, so long as it will fit in his knapsack, and he can carry it.",
        "He knows that he can carry no more than  a particalar value of maximum weight in total;  and that the capacity of his knapsack has a limited volume.",
        "Looking just above the bar codes on the items he finds their weights and volumes.  He digs out his recent copy of a  financial paper and gets the value of each item.",
        "He can only take whole units of any item, but there is much more of any item than he could ever carry.",
        "Write a function that takes an array of objects, maximum weight, and maximum volume as parameters. Each object has 4 attributes: name, value, weight, and volume. The function should return the maximum value of items the traveller can take with him."
      ],
```

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, sorry, I forgot that I added one set of `$$` to the challenge Kaprekar numbers. Maybe that's what's causing the build to fail now?

Here's the description from my last commit:

```
      "description": [
        "A positive integer is a <a href=\"https://en.wikipedia.org/wiki/Kaprekar number\">Kaprekar number</a> if:",
        "<ul><li>It is 1</li><li>The decimal representation of its square may be split once into two parts consisting of positive integers which sum to the original number. </li></ul>",
        "Note that a split resulting in a part consisting purely of 0s is not valid, as 0 is not considered positive.Example Kaprekar numbers:",
        "<ul><li>$$2223$$ is a Kaprekar number, as $2223 * 2223 = 4941729$, $4941729$ may be split to $494$ and $1729$, and $494 + 1729 = 2223$.</li><li>The series of Kaprekar numbers is known as <a href=\"http://rosettacode.org/wiki/oeis:A006886\">A006886</a>, and begins as $1, 9, 45, 55, ...$.</li></ul>",
        "Write a function that takes a number $n$, a base $bs$, and returns true if the number is a Kaprekar number for the given base. Otherwise, the function returns false."
      ],
```

**Comment by NitronR** [comment]
The Travis log says that its because of the earlier two commits:
 Update rosetta-code.json
Update descriptions in rosetta-code.json 

I think all commits should have titles in particular format. I am trying to squash those two commits right now.

**Comment by scissorsneedfoodtoo** [comment]
Shoot, those were the ones I was trying to push earlier. I'm sorry about that. I'm trying to search for a solution, too. Perhaps squashing them like you said would be the easiest thing to do.

**Comment by NitronR** [comment]
I have resolved the issue. Thanks for bearing with me!!

**Comment by scissorsneedfoodtoo** [comment]
@NitronR, no need to thank me--should be the other way around. Thank you for bearing with me!

Just to check, @raisedadead, would it be okay to merge into this feat/interview-prep branch?

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo Yes, it fine to merge into feat branch for now.

**Comment by scissorsneedfoodtoo** [comment]
Alright! Everything LGTM. Thanks again for everything @NitronR.

**Pull request merged**
