### PR TITLE
fix(challenges): update regular expression that fails

### LINKED ISSUE #55: Regular Expression Error in Test for Debugging Challenge
**Referencing Issue #17387 in freeCodeCamp/freeCodeCamp:**
In the "Debugging: Understanding the Differences between the freeCodeCamp and Browser Console" challenge, a correct solution cannot pass because of a test failing due to the following:
```
// running test
invalid regexp group
// tests completed
```

It has been determined that this is likely because the negative look behind regular expression used is not fully implemented in Firefox yet.

**To Reproduce**
1. Go to [the challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console).
2. Solve the challenge per instructions.
3. Run the Tests.

**Expected behavior**
The challenge should pass if the regular expression in the test is changed (this will be duplicating a PR that was closed under _freeCodeCamp/freeCodeCamp_ so that it can be implemented here).

**Desktop (please complete the following information):**
 - OS: macOS High Sierra v10.13.5
 - Browser: Firefox
 - Version: 60.0.2

### PR DESCRIPTION
**Pull request by matthew-t-smith**
Changes regular expression in testString to remove negative look behind that is not implemented
across all browsers.

ISSUES CLOSED: #55

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
  Targets new `dev` branch of curriculum
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #55 
https://github.com/freeCodeCamp/freeCodeCamp/issues/17387

#### Description
This replicates a PR that was closed on freeCodeCamp (noted in the Issue #55 ) in order to remove a negative look behind used in the regular expression in a test. This is not fully implemented in Firefox yet, but the new expression should take care of the testing as it should.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@matthew-t-smith, thank you for moving your PR to this repo!

I'm sorry, there's just one thing I noticed. Not sure why, but a lot of the spacing was added to the tests objects. Maybe one of the tests or a linter added all of these line breaks? Unfortunately, I'm not sure if we can merge this as the formatting is quite a bit different than the other seed files.

This isn't the challenge you're updating, but here's an example of the format for the tests.

```
      "tests": [
        {
          "text": "Your code should use <code>console.log()</code> to check the value of the variable <code>a</code>.",
          "testString": "assert(code.match(/console\\.log\\(a\\)/g), 'Your code should use <code>console.log()</code> to check the value of the variable <code>a</code>.');"
        }
      ],
```

Would you be able to update this pull request so that the tests look like the one above, without all of the line breaks?

**Comment by matthew-t-smith** [comment]
@scissorsneedfoodtoo  I just updated removing all the line breaks. It was happening _during_ the `npm run commit` on my computer. It has something to do with the character length of each line. Shorter titles and test strings didn't jump.

However, now my Travis CI has 1 failing check. I'll look into this evening.

**Comment by scissorsneedfoodtoo** [comment]
@matthew-t-smith, you're right, I checked on my local machine and the same happens automatically. I checked some other challenge files and you're right--shorter titles and test strings are all on the same line. Sorry about that! Didn't realize until now.

Could you roll back to your previous commit, or just run `npm run commit` again to get things back the way they were? I'm sorry again for all the trouble.

**Comment by raisedadead** [comment]
We have turned on [prettier](https://prettier.io/) formatting. Its worth investigating if this is okay or not for certain files. Is the spacing an issue on the  final outputs?

**Comment by scissorsneedfoodtoo** [comment]
@raiseadead, good point. Seems like a lot of the basic Javascript files were formatted. I can take a quick look and see if the spacing is an issue before @matthew-t-smith makes any further changes.

**Comment by scissorsneedfoodtoo** [comment]
@matthew-t-smith, awesome! That was so fast. Thank you again for making all of these changes and going back and forth like that. Everything LGTM :+1:

**Pull request merged**
