### PR TITLE
fix(challenges): fixed RegEx for Template Literals JavaScript challenge

### LINKED ISSUE #65: Regex to test for Template Literals is incorrect
**Describe the bug**
The regex string to test is the user has correctly used template literals is incorrect and the test fails when it should not.
Some of the escape characters in the string are not correctly entered, causing the error.

**To Reproduce**
1. Go to ES6: Create Strings using Template Literals
2. Complete the task
3. Click on Run the Tests
4. The test for "Template strings were used" will fail.

**Expected behavior**
The test should pass when template literals are correctly used.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version:  67.0.3396.99 (Official Build) (64-bit)

I'm happy to correct this issue.

### PR DESCRIPTION
**Pull request by gforce2k5**
ISSUES CLOSED: #65

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch of freeCodeCamp/curriculum.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #65

### CODE REVIEW

**Comment by RobAnthony01** [comment]
This is still not fully correct. There is only one backslash in front of the double quote symbol and there needs to be two.

**Comment by gforce2k5** [comment]
I’ll fix it :) thank you for noricing

**Comment by gforce2k5** [comment]
the backslash before the quotes is to escape the quotes inside the string and not for the regex, so only one backslash needed

**Comment by scissorsneedfoodtoo** [comment]
@gforce2k5, thank you for submitting a PR for this. I think you're right, the double backslashes would be interpreted as just a single backslash, or an escaped character, so they're not needed. Also, great catch by adding the double backslashes in front of the forward slash in </li> at the end there--missed that on my last pass.

Just one thing, could you change the message back? The test is meant to see if the user actually used template strings to complete the challenge. So:

```
        {
          "text": "Template strings were used.",
          "testString":
            "getUserInput => assert(getUserInput('index').match(/`<li \\s*class\\s*=\\s*(\"\\s*text-warning\\s*\"|'\\s*text-warning\\s*')\\s*>\\s*\\$\\s*\\{(\\s*\\w+\\s*|\\s*\\w+\\s*\\[\\s*[\\w]+\\s*\\]\\s*)\\}\\s*<\\s*\\/li\\s*>`/g), 'Template strings were used.');"
        }
```

Added a period to both the text and testString messages.

**Pull request closed without merging**
