### PR TITLE
fix(challenges): add note at bottom of description in d3 challenge

### PR DESCRIPTION
**Pull request by nischaldutt**
Add a short message in note at bottom of description in d3 challenge

ISSUES CLOSED: https://github.com/freeCodeCamp/freeCodeCamp/issues/17767

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [x] All new and existing tests pass the command `npm test`.
- [x] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17767

### CODE REVIEW

**Comment by nischaldutt** [comment]
yes sir, I'll look forward to it.

**Comment by scissorsneedfoodtoo** [comment]
@nischaldutt, alright! Looking forward to your updated description.

**Comment by nischaldutt** [comment]
thank you sir, I've update the pull request as specified 😊

**Comment by nischaldutt** [comment]
thank you sir, I've update the pull request as specified 😊
Do I need to add further description ?

**Comment by scissorsneedfoodtoo** [comment]
Yes, would you mind updating the note so it reads something like the following?

`"<strong>Note</strong><br>The circles won't be visible because we haven't set their attributes yet. We'll do that in the next challenge."`

To do that, make sure you're on the right branch with `git checkout add/note-in-description-d3-challenge`. Make the changes and add the file with `git add challenges/04-data-visualization/data-visualization-with-d3.json`. Then you'll need to use `git commit --amend` to amend your current commit message. It's fine now, so just exit out after that command. Finally, just push back to your branch with `git push -f origin dev` and we'll see the changes reflected here.

Let me know if you need any help throughout the process!

**Comment by nischaldutt** [comment]
Thanks for the valuable response.

**Comment by scissorsneedfoodtoo** [comment]
@nischaldutt, I'm not seeing the changes here, and I think it's due to an error in the instructions I gave earlier. I'm very sorry, but I believe I told you to force push to the dev branch rather than the one you created for this PR.

Let's try again:

All you should have to do is make sure you're on the right branch with `git checkout add/note-in-description-d3-challenge`. Then just run `git push -f origin add/note-in-description-d3-challenge`. After that we should see the changes you made here.

To get your dev branch back to normal, switch to it with `git checkout dev`, then run `git pull --rebase upstream dev`. Finally, all you should have to do is force push to the dev branch with `git push -f`.

Sorry again for the trouble!

**Comment by nischaldutt** [comment]
Makes sense, thanks for such a constructive response 
I've committed the changes

**Comment by scissorsneedfoodtoo** [comment]
:sparkles: :sparkles: :sparkles: Awesome! Congratulations on your first contribution to freeCodeCamp! :sparkles: :sparkles: :sparkles:

Thank you for submitting a PR for this issue, @nischaldutt. We're all really looking forward to your next contribution! And sorry again for the incorrect directions earlier -- I'll be more careful next time you contribute.

**Comment by nischaldutt** [comment]
Thanks for guiding me throughout the process. I learned allot from it

**Pull request merged**
